---
name: Catalyst-Controller-Combine
version: 0.06
author:
  - 'Wolfgang Kinkeldei <wki@cpan.org>'
abstract: Combine JS/CSS Files
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Catalyst::Runtime: 5.80
  File::stat: 1.00
  FindBin: 1.47
  List::Util: 1.19
  Moose: 0.74
  Path::Class: 0.16
  Test::Builder: 0.86
  Test::Builder::Tester: 1.18
  Test::Exception: 0.27
  Test::Harness: 3.14
  Test::More: 0.86
  perl: 5.8.8
provides:
  Catalyst::Controller::Combine:
    file: lib/Catalyst/Controller/Combine.pm
    version: 0.06
  Catalyst::Helper::Controller::Combine:
    file: lib/Catalyst/Helper/Controller/Combine.pm
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
